#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BindingTest.Resource", IsApplication=true)]

namespace BindingTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int WheelArrayDefault = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int WheelArrayWeek = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int wheel_atmospheric = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int wheel_curtain = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int wheel_curtain_color = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int wheel_curved = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int wheel_cyclic = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int wheel_data = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int wheel_indicator = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int wheel_indicator_color = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int wheel_indicator_size = 2130771981;
			
			// aapt resource value: 0x7f010012
			public const int wheel_item_align = 2130771986;
			
			// aapt resource value: 0x7f010009
			public const int wheel_item_space = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int wheel_item_text_color = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int wheel_item_text_size = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int wheel_maximum_width_text = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int wheel_maximum_width_text_position = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int wheel_same_width = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int wheel_selected_item_position = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int wheel_selected_item_text_color = 2130771972;
			
			// aapt resource value: 0x7f010008
			public const int wheel_visible_item_count = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int WheelIndicatorSize = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int WheelItemSpace = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int WheelItemTextSize = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int WheelMargins = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int center = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int goto_btn = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int left = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int main_wheel_center = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int main_wheel_left = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int main_wheel_right = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int right = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int wheel_date_picker_day = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int wheel_date_picker_day_tv = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int wheel_date_picker_month = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int wheel_date_picker_month_tv = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int wheel_date_picker_year = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int wheel_date_picker_year_tv = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int view_wheel_date_picker = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Day = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Hello = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Month = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Year = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] WheelPicker = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 16
			public const int WheelPicker_wheel_atmospheric = 16;
			
			// aapt resource value: 14
			public const int WheelPicker_wheel_curtain = 14;
			
			// aapt resource value: 15
			public const int WheelPicker_wheel_curtain_color = 15;
			
			// aapt resource value: 17
			public const int WheelPicker_wheel_curved = 17;
			
			// aapt resource value: 10
			public const int WheelPicker_wheel_cyclic = 10;
			
			// aapt resource value: 0
			public const int WheelPicker_wheel_data = 0;
			
			// aapt resource value: 11
			public const int WheelPicker_wheel_indicator = 11;
			
			// aapt resource value: 12
			public const int WheelPicker_wheel_indicator_color = 12;
			
			// aapt resource value: 13
			public const int WheelPicker_wheel_indicator_size = 13;
			
			// aapt resource value: 18
			public const int WheelPicker_wheel_item_align = 18;
			
			// aapt resource value: 9
			public const int WheelPicker_wheel_item_space = 9;
			
			// aapt resource value: 3
			public const int WheelPicker_wheel_item_text_color = 3;
			
			// aapt resource value: 2
			public const int WheelPicker_wheel_item_text_size = 2;
			
			// aapt resource value: 6
			public const int WheelPicker_wheel_maximum_width_text = 6;
			
			// aapt resource value: 7
			public const int WheelPicker_wheel_maximum_width_text_position = 7;
			
			// aapt resource value: 5
			public const int WheelPicker_wheel_same_width = 5;
			
			// aapt resource value: 1
			public const int WheelPicker_wheel_selected_item_position = 1;
			
			// aapt resource value: 4
			public const int WheelPicker_wheel_selected_item_text_color = 4;
			
			// aapt resource value: 8
			public const int WheelPicker_wheel_visible_item_count = 8;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
